//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.20 at 05:52:42 PM CEST 
//

package com.ibtim.flexo.webservice.previa;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.ibtim.flexo.webservice.previa package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _IsExisteExpedienteResponseIsExisteExpedienteReturn_QNAME = new QName(
			"http://previa.webService.flexo.ibtim.com",
			"isExisteExpedienteReturn");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.ibtim.flexo.webservice.previa
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link IsExisteExpediente }
	 * 
	 */
	public IsExisteExpediente createIsExisteExpediente() {
		return new IsExisteExpediente();
	}

	/**
	 * Create an instance of {@link ReqType }
	 * 
	 */
	public ReqType createReqType() {
		return new ReqType();
	}

	/**
	 * Create an instance of {@link IsExisteExpedienteResponse }
	 * 
	 */
	public IsExisteExpedienteResponse createIsExisteExpedienteResponse() {
		return new IsExisteExpedienteResponse();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://previa.webService.flexo.ibtim.com", name = "isExisteExpedienteReturn", scope = IsExisteExpedienteResponse.class)
	public JAXBElement<Boolean> createIsExisteExpedienteResponseIsExisteExpedienteReturn(
			Boolean value) {
		return new JAXBElement<Boolean>(
				_IsExisteExpedienteResponseIsExisteExpedienteReturn_QNAME,
				Boolean.class, IsExisteExpedienteResponse.class, value);
	}

}
