//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.20 at 05:52:42 PM CEST 
//

package com.ibtim.flexo.webservice.previa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for reqType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="reqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bancoId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operacionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reqType", propOrder = { "bancoId", "operacionId" })
public class ReqType {

	@XmlElement(required = true)
	protected String bancoId;
	@XmlElement(required = true)
	protected Integer operacionId;

	/**
	 * Gets the value of the bancoId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBancoId() {
		return bancoId;
	}

	/**
	 * Sets the value of the bancoId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBancoId(String value) {
		this.bancoId = value;
	}

	/**
	 * Gets the value of the operacionId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public Integer getOperacionId() {
		return operacionId;
	}

	/**
	 * Sets the value of the operacionId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOperacionId(Integer value) {
		this.operacionId = value;
	}

}
