//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.20 at 05:52:42 PM CEST 
//


package com.ibtim.flexo.webservice.previa;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isExisteExpedienteReturn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isExisteExpedienteReturn"
})
@XmlRootElement(name = "isExisteExpedienteResponse")
public class IsExisteExpedienteResponse {

    @XmlElementRef(name = "isExisteExpedienteReturn", namespace = "http://previa.webService.flexo.ibtim.com", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> isExisteExpedienteReturn;

    /**
     * Gets the value of the isExisteExpedienteReturn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getIsExisteExpedienteReturn() {
        return isExisteExpedienteReturn;
    }

    /**
     * Sets the value of the isExisteExpedienteReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setIsExisteExpedienteReturn(JAXBElement<Boolean> value) {
        this.isExisteExpedienteReturn = value;
    }

}
